FROM node:14-alpine AS build

LABEL MAINTAINER="dmeckers"

WORKDIR /app

RUN apk update && apk upgrade

COPY package*.json ./

RUN npm install && apk add --no-cache ffmpeg

COPY . .

FROM node:14-alpine

LABEL MAINTAINER="dmeckers"

RUN apk update && apk upgrade

RUN addgroup -S workers && adduser -S worker -G workers

WORKDIR /app

RUN apk add --no-cache ffmpeg

COPY --from=build /app /app

RUN chown -R worker:workers /app

RUN npm install -g nodemon typescript

USER worker

EXPOSE 8000
EXPOSE 1935

ENTRYPOINT ["nodemon", "--config", "nodemon.json"]